name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  version:
    runs-on: ubuntu-latest
    container: gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1
    steps:
      - run: |
          GITVERSION=$(/tools/dotnet-gitversion "/github/workflow" /output json /showvariable FullSemVer)
          echo $GITVERSION
  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet restore DynamicExpresso.sln
    - run: dotnet build DynamicExpresso.sln --no-restore -c Release /p:Version=$(GitVersion.NuGetVersionV2)
    - run: dotnet test DynamicExpresso.sln --no-restore -c Release --verbosity normal -f netcoreapp3.1
    - run: dotnet test DynamicExpresso.sln --no-restore -c Release --verbosity normal -f netcoreapp5.0
